### ISSUE TITLE
Passenger compatibility ?

### ISSUE THREAD

**Issue by kamisama** [logentries/le_ruby#36]
I'm trying to make Logentries work with a Rails 4.2 app, but the gem seems unable to connect to the API.
The debug log:

```
D, [2015-01-16T07:31:53.007004 #4917] DEBUG -- : LE: Unable to connect to Logentries due to timeout(Connection timed out - connect(2) for "api.logentries.com" port 10000)
D, [2015-01-16T07:31:53.007103 #4917] DEBUG -- : LE: Waiting for 11ms
D, [2015-01-16T07:32:04.007221 #4917] DEBUG -- : LE: Reopening connection to Logentries API server
D, [2015-01-16T07:35:13.391005 #4917] DEBUG -- : LE: Unable to connect to Logentries due to timeout(Connection timed out - connect(2) for "api.logentries.com" port 10000)
D, [2015-01-16T07:35:13.391087 #4917] DEBUG -- : LE: Waiting for 18ms
D, [2015-01-16T07:35:31.391209 #4917] DEBUG -- : LE: Reopening connection to Logentries API server
```

It works well with Puma and Webrick, but the connection always timeout with Passenger.
Server should have no problems connecting to an external service via UDP, since the app is already sending data to an external statsD service via UDP.

Does passenger needs additional config to make it works ?

**Comment by StephenHynes7** [comment]
@kamisama Hmm what does your constructor look like? UDP support was only recently added so you would have to explicitly set it in the constructor 
```
Rails.logger = Le.new('', :udp_port => 13287)
```

Where the port is a port you obtained from Logentries when creating a plain TCP/UDP log.

**Comment by kamisama** [comment]
Sorry, I meant Tcp instead of udp. I am connecting via the tcp with token
option.

**Comment by kamisama** [comment]
I just tested with webrick on my production server,  and it's not working either. So the issue was not with passenger, but with the server itself. Do you provide some kind of tools to debug the connection issue ?

**Comment by StephenHynes7** [comment]
Can you ssh into that environment try the following for me.

telnet api.logentries.com 10000

And see if that connects? If it doesn't then that would be the smoking gun.

**Comment by kamisama** [comment]
it seems stucked ...

```
$ telnet api.logentries.com 10000
$ Trying 54.247.179.233...
$ Trying 46.137.78.79...
$ Trying 46.51.172.0...
```

When trying the same command on my local env, it connected immediately.

**Comment by StephenHynes7** [comment]
Okay cool that narrows things down.

Can you try the same but to data.logentries.com 10000 and if that doesn't work try data.logentries.com 80

Regards,
Stephen

**Comment by kamisama** [comment]
```
$ telnet data.logentries.com 10000
$ Trying 54.246.89.117...
```

Then stucked

Port 80 seems to work

```
$ telnet data.logentries.com 80
$ Trying 79.125.113.75...
$ Connected to data.logentries.com.
Escape character is '^]'.
```

**Comment by StephenHynes7** [comment]
Great that's some progress. So the Ruby library currently uses port 10000 and api.logentries. But really there is nothing stopping you from changing this to data.logentries.com and port 80.

**Comment by kamisama** [comment]
The initializer method does not provide option to define a custom host and port for the TCP connection. I'll have to monkeypath the Le::Host::http class, right ?

**Comment by StephenHynes7** [comment]
Correct, you would have to change these values here https://github.com/logentries/le_ruby/blob/master/lib/le/host/http.rb#L10

**Comment by kamisama** [comment]
Thanks @StephenHynes7 , it works ;)

Just for my information, what was the issue ? Is it logentries server filtering connections based on IP, or is it some config issue on my server ?

**Comment by mrud** [comment]
It is either your server or provider. Somehow you haven't been able to connect to port 10000 on logentries which we use per default for submitting loglines. 

This means that either you or your provider have a firewall preventing access to logentries on port 10000.
