### ISSUE TITLE
Use data.logentries.com and ports 80/443

### ISSUE THREAD

**Issue by StephenHynes7** [logentries/le_ruby#37]
We should look to move the library to use data.logentries.com as our endpoint and forward logs over ports 80 and 443.

**Comment by stakach** [comment]
Very much for this! Or at least make it an option - we have a few enterprise installations where they won't open ports and I am forced to use loggly

**Comment by stakach** [comment]
@StephenHynes7 any news on this?

**Comment by stakach** [comment]
@StephenHynes7 is ruby support being phased out? No updates for quite a while...
Would be good to see some of the features from the Python library ported over to the Ruby library...

This for example
https://github.com/logentries/le_python/commit/86420056322c92229f6774e9dd8f6ae56535226a

**Comment by StephenHynes7** [comment]
@stakach No it's not, granted there hasn't been a lot of movement here for a while. Ill review things and see what I can do to get things more active again here. For the most part though this would be considered (at least from my point of view) one of our more complete libraries with a minimum amount of outstanding issues.

**Comment by stakach** [comment]
Thanks @StephenHynes7 - much appreciated - we still have a few sites with local logging as they won't open the ports. Very frustrating.
